markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Shelter"
markdown: rdiscount

author: "Emilo"
atom-baseurl: "http://galaxymiao.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: building
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
